### ISSUE TITLE
no LICENSE file

### ISSUE THREAD

**Issue by stayhydated** [WrathChaos/react-native-segmented-control-2#5]
Hey, I modified your implementation to suit my use case, but I don't see any LICENSE file linked to your name in this repository.

**Comment by kuraydev** [comment]
Helloo @FranzJvezNiceAxa 
https://github.com/WrathChaos/react-native-segmented-control-2#license

It does not have a separate license file but it is MIT so feel free to use it :) 

Also, share the modification if you can so maybe we can improve the library
